### ISSUE TITLE
Question: header transform

### ISSUE THREAD

**Issue by Tungsten78** [RedRiverSoftware/FromHeaderAttribute#5]
While using this attribute I ran into trouble with parameters containing upper-case characters.  Looking closer at the code a transform is being applied add hyphens.

From your [blog post](https://river.red/binding-to-and-validating-http-headers-with-web-api-2/), it appears that this transformation might be specific to your example implementation (ie: to fit with pagination parameters).  Is this the case?

**Comment by kierenj** [comment]
Yes, that's correct.  That was based on the common convention in each case: C# preferring `TitleCase` for when there are multiple words, and HTTP custom headers working `X-Like-This`
